apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-deployment
  labels:
    app: vpromc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromc
  template:
      metadata:
        labels:
          app: vprodb
      spec:
        containers:
        - name: vpromc
          image: memcached
          ports:
          - containerPort: 11211